/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserService } from "../user.service";
import { Public } from "../../decorators/public.decorator";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { EventRegistrationFindManyArgs } from "../../eventRegistration/base/EventRegistrationFindManyArgs";
import { EventRegistration } from "../../eventRegistration/base/EventRegistration";
import { EventRegistrationWhereUniqueInput } from "../../eventRegistration/base/EventRegistrationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @Public()
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: {
        ...data,

        branch: data.branch
          ? {
              connect: data.branch,
            }
          : undefined,
      },
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        profilePath: true,
        roles: true,
        updatedAt: true,
        username: true,
        usn: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        profilePath: true,
        roles: true,
        updatedAt: true,
        username: true,
        usn: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        profilePath: true,
        roles: true,
        updatedAt: true,
        username: true,
        usn: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @Public()
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          branch: data.branch
            ? {
                connect: data.branch,
              }
            : undefined,
        },
        select: {
          branch: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          profilePath: true,
          roles: true,
          updatedAt: true,
          username: true,
          usn: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          branch: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          profilePath: true,
          roles: true,
          updatedAt: true,
          username: true,
          usn: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/eventRegistrations")
  @ApiNestedQuery(EventRegistrationFindManyArgs)
  async findManyEventRegistrations(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<EventRegistration[]> {
    const query = plainToClass(EventRegistrationFindManyArgs, request.query);
    const results = await this.service.findEventRegistrations(params.id, {
      ...query,
      select: {
        createdAt: true,

        event: {
          select: {
            id: true,
          },
        },

        feedback: true,
        id: true,
        isAttended: true,
        teamMembers: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @Public()
  @common.Post("/:id/eventRegistrations")
  async connectEventRegistrations(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EventRegistrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventRegistrations: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Patch("/:id/eventRegistrations")
  async updateEventRegistrations(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EventRegistrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventRegistrations: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Delete("/:id/eventRegistrations")
  async disconnectEventRegistrations(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EventRegistrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventRegistrations: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
